"""initial schema

Revision ID: 8e0458f72b36
Revises: 
Create Date: 2026-08-11 18:21:23.390613
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.Enum('email', 'slack', 'crm', 'chat_widget', 'webhook', name='integrationtype'), nullable=False),
    sa.Column('status', sa.Enum('connected', 'disconnected', 'error', name='integrationstatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('teams',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('routing_rules',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('target_team_id', sa.String(length=36), nullable=False),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('agent', 'team_lead', 'admin', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'login', 'assign', 'status_change', 'feedback', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requester_name', sa.String(length=255), nullable=False),
    sa.Column('requester_email', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.Enum('email', 'chat', 'phone', 'web_form', 'social', name='channelenum'), nullable=False),
    sa.Column('status', sa.Enum('new', 'open', 'in_progress', 'pending', 'resolved', 'closed', name='ticketstatus'), nullable=False),
    sa.Column('urgency', sa.Enum('low', 'medium', 'high', 'critical', name='urgencyenum'), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('subcategory', sa.String(length=120), nullable=True),
    sa.Column('assigned_to_id', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_events',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('created', 'warning', 'breached', 'resolved', name='slaeventtype'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('breached', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_events_ticket_id'), 'sla_events', ['ticket_id'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('sender_type', sa.Enum('customer', 'agent', 'system', name='messagesendertype'), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.create_table('ticket_predictions',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('subcategory', sa.String(length=120), nullable=True),
    sa.Column('urgency', sa.Enum('low', 'medium', 'high', 'critical', name='urgencyenum'), nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', name='sentimentenum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('predicted_team_id', sa.String(length=36), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['predicted_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_predictions_ticket_id'), 'ticket_predictions', ['ticket_id'], unique=False)
    op.create_table('feedback_corrections',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('original_category', sa.String(length=120), nullable=True),
    sa.Column('corrected_category', sa.String(length=120), nullable=True),
    sa.Column('original_urgency', sa.Enum('low', 'medium', 'high', 'critical', name='urgencyenum'), nullable=True),
    sa.Column('corrected_urgency', sa.Enum('low', 'medium', 'high', 'critical', name='urgencyenum'), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['ticket_predictions.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_corrections_ticket_id'), 'feedback_corrections', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_corrections_ticket_id'), table_name='feedback_corrections')
    op.drop_table('feedback_corrections')
    op.drop_index(op.f('ix_ticket_predictions_ticket_id'), table_name='ticket_predictions')
    op.drop_table('ticket_predictions')
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_sla_events_ticket_id'), table_name='sla_events')
    op.drop_table('sla_events')
    op.drop_table('tickets')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('routing_rules')
    op.drop_table('teams')
    op.drop_table('model_versions')
    op.drop_table('integrations')
    # ### end Alembic commands ###
